### ISSUE TITLE
A declared, settable field cannot be set unless the note already carries it

### ISSUE THREAD

**Issue by agustinvalencia** [agustinvalencia/cuaderno#593]
## What happens

`frontmatter set` can only *rewrite* a key that is already present in the note. A field that is declared, typed and `settable = true` is still unwritable if the note does not already carry it:

```text
Error: frontmatter has no field 'handle' to rewrite
```

This is a different failure from #581. There the field is **undeclared**, and the error names the fix:

```text
note type 'contact' has no declared field 'name' — declare it under [schemas.contact.fields.name] to make it settable
```

Here the declaration is already in place and correct. The error names no fix, because from the vault's side there is nothing left to declare.

## Reproduction

`cdno 0.37.0`, fresh vault. Config:

```toml
[note_types.contact]
folder = "contacts"
required = ["name"]
optional = ["handle"]
title_field = "name"

[schemas.contact.fields.handle]
type = "string"
settable = true

[schemas.contact.fields.name]
type = "string"
settable = true
```

Create a note that omits the optional field, which is what a minimal template produces:

```sh
cdno note create contact --title "Ada Lovelace" --field name="Ada Lovelace"
```

```markdown
---
type: contact
name: Ada Lovelace
---
```

Then:

```sh
$ cdno frontmatter set contacts/ada-lovelace.md name "Ada L"
Set name on contacts/ada-lovelace.md          # declared + present -> works

$ cdno frontmatter set contacts/ada-lovelace.md handle "forge:alovelace"
Error: frontmatter has no field 'handle' to rewrite   # declared + absent -> refused
```

The MCP `set_frontmatter` fails the same way.

## Why it matters

The backfill case is the main reason to have `settable` optional scalars at all: a handle, an email or a phone number that turns up months after the note was written. That case is exactly the one that cannot happen, because an optional field is by definition absent until something writes it — and nothing can.

It also penalises the minimal template that the docs recommend. A template that renders every declared-but-unset optional field emits literal `{{ field }}` placeholders, and an unset list field then parses as a YAML map, which silently drops the note from the index. So the safe template omits optional fields — and the safe template is the one that makes them permanently unwritable. The two pieces of advice are individually right and jointly a trap.

The only way through is a hand-edit plus `cdno reindex`, which is what `set_frontmatter` exists to avoid.

## Proposal

When a field is declared for the type and `settable`, `frontmatter set` should insert it if absent rather than requiring an existing key to overwrite. The declaration already carries the type, so the value can be validated on insert exactly as on rewrite. Insertion position can follow the declared field order so notes stay consistent.

If refusing to insert is deliberate, the error should say so and name the remedy, rather than describing an internal precondition.

## Acceptance

- [ ] `frontmatter set` adds a declared, settable, absent scalar field to a note
- [ ] The inserted value is type-checked as the declaration specifies
- [ ] An undeclared field still fails with the #581 message, unchanged
- [ ] Non-scalar fields (lists) stay non-settable, as today
